### ISSUE TITLE
Incorrect .navbar-nav margin

### ISSUE THREAD

**Issue by albv** [jlong/sass-bootstrap-defunct#96]
In _navbar.scss:

``` scss
.navbar-nav {
  margin: ($navbar-padding-vertical / 2) -$navbar-padding-horizontal;
  ...
}
```

In original LESS version it supposed to set both horizontal and vertical margins, but in SASS it's simply subtract values. So I think it should be:

``` scss
.navbar-nav {
  margin: ($navbar-padding-vertical / 2) (-$navbar-padding-horizontal);
  ...
}
```
